### PR TITLE
Link to F-Droid

### PR DESCRIPTION
**Pull request by licaon-kter**
...you want a desaturated logo?

Fix https://github.com/onionshare/onionshare-website/issues/40

### CODE REVIEW

**Comment by SaptakS** [comment]
Yes, A desaturated logo would be great! @grote can you confirm the link and information change in this PR is correct? Apart from that, looks good to me.

**Comment by licaon-kter** [comment]
Umm, desaturated in what way, just gray-ish?

**Comment by eighthave** [comment]
I think there is a monochrome version somewhere, @ConnyDuck added one to fdroidclient

**Comment by licaon-kter** [comment]
better? :smile:

**Comment by SaptakS** [comment]
I don't hate it! @glenn-sorrentino in case you have any feedback, else going to merge this.

**Comment by licaon-kter** [comment]
I can desaturate it in GIMP in like 4 ways, but not sure I want it too whiteish so the head and body are closer, nor too dark so it stays in theme

how can I preview this PR page?

**Pull request merged**
